spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/plus?characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

mybatis-plus:
  type-enums-package: com.qiuwei.mybatisplus.*.enums
#  注意核心文件和mapper映射文件路劲的扫描问题
  config-location: "classpath:mapper/mybatis-config.xml"
  mapper-locations: "classpath*:mapper/*/*Mapper.xml"
